### PR TITLE
More closely match Axum + Actix Leptos server implementation

### PR DESCRIPTION
**Pull request by ogghead**
## Why is this needed?
1. More closely match how optional params are handled in [Axum ](https://github.com/leptos-rs/leptos/blob/main/integrations/axum/src/lib.rs#L1329)and [Actix ](https://github.com/leptos-rs/leptos/blob/main/integrations/actix/src/lib.rs#L1026) server implementations
2. Match [route context implementation in Axum server](https://github.com/leptos-rs/leptos/blob/main/integrations/axum/src/lib.rs#L1311)

## Testing
* Tested with a Spin app using local path dependency on leptos_wasi and it still works as expected + deploys to Spin cloud

### CODE REVIEW

**Comment by ogghead** [comment]
@raskyld @benwis I appreciate reviews when ya'll have time!

**Comment by raskyld** [comment]
LGTM!

**Review by raskyld — APPROVED** [review]

**Comment by benwis** [comment]
LGTM!

**Comment by ogghead** [comment]
Thank you both for the quick reviews! I don't think I have the ability to merge sadly

**Pull request merged**
